version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
     - 3000:3000
    depends_on:
      - db

  #db: # MySQLが起動するコンテナ
  #  image: mysql:8.0.21
  #  volumes:
  #    - mysql_data:/var/lib/mysql # データの永続化
  
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - 3306:3306

#volumes:
#  mysql_data: # データボリュームの登録