version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
     - 3000:3000
#    depends_on:
#      db:
#        condition: service_healthy

#  db:
#    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
#    command: mysqld --default-authentication-plugin=mysql_native_password
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
#      MYSQL_DATABASE: $MYSQL_DATABASE
      # MYSQL_USER: $MYSQL_USER
      # MYSQL_PASSWORD: $MYSQL_PASSWORD
#    ports:
#      - 3306:3306
#    healthcheck:
#        test: mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD
    #volumes:
    #  - mysql_data:/var/lib/mysql 

#volumes:
#  mysql_data: # データボリュームの登録