version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
     - 3000:3000
    depends_on:
      - db

  db: # MySQLが起動するコンテナ
    image: mysql:8.0.21
    volumes:
      - mysql_data:/var/lib/mysql # データの永続化
    command: --default-authentication-plugin=mysql_native_password # 認証方式を8系以前のものにする。
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'rails6_development'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
    ports:
      - 3306:3306

volumes:
  mysql_data: # データボリュームの登録